version: Build {build}

os: Visual Studio 2022

configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  TARGET_BUILD_VERSION: '2.1.0'

nuget:
  disable_publish_on_pr: true

before_build:
  - dotnet --info
  - dotnet restore .\src\MysticMind.PostgresEmbed.sln

build_script:
  - dotnet build .\src\MysticMind.PostgresEmbed.sln --configuration %CONFIGURATION% /p:Version=%TARGET_BUILD_VERSION%

after_build:
  - dotnet pack .\src\MysticMind.PostgresEmbed --configuration %CONFIGURATION% /p:Version=%TARGET_BUILD_VERSION%

test_script:
  - dotnet test .\src\MysticMind.PostgresEmbed.Tests\MysticMind.PostgresEmbed.Tests.csproj --configuration %CONFIGURATION%

artifacts:
  - path: '**\MysticMind.PostgresEmbed.*.nupkg' # find all NuGet packages recursively

deploy:
  provider: NuGet
  api_key:
    secure: z0rU/GnC8lDmV0kSMNZ6izcFVLCSkn7PpC6rQiGL+XnaQW/uGnqFZPHns8jEzNRj
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
  skip_symbols: true

