version: Build {build}

os: Visual Studio 2022

configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  TARGET_BUILD_VERSION: '3.0.0'

nuget:
  disable_publish_on_pr: true

before_build:
  - dotnet --info
  - dotnet restore .\src\MysticMind.PostgresEmbed.sln

build_script:
  - dotnet build .\src\MysticMind.PostgresEmbed.sln --configuration %CONFIGURATION% /p:Version=%TARGET_BUILD_VERSION%

after_build:
  - dotnet pack .\src\MysticMind.PostgresEmbed --configuration %CONFIGURATION% /p:Version=%TARGET_BUILD_VERSION%

test_script:
  - dotnet test .\src\MysticMind.PostgresEmbed.Tests\MysticMind.PostgresEmbed.Tests.csproj --configuration %CONFIGURATION%

#artifacts:
#  - path: '**\MysticMind.PostgresEmbed.*.nupkg' # find all NuGet packages recursively
#
#src/MysticMind.PostgresEmbed/MysticMind.PostgresEmbed.csprojdeploy:
#  provider: NuGet
#  api_key:
#    secure: iGLl9LCDfrevtXMZSzGsL00+nm/hVrFTLpbcgMuTP4S4El6/f09KhrsHAGj9VnCS
#  artifact: /.*\.nupkg/
#  on:
#    APPVEYOR_REPO_TAG: true
#  skip_symbols: true

